#!/bin/bash
# Check for direct modifications to /src files that should only be auto-generated
# This helps prevent the common mistake of editing files in /src instead of source-documents/

# Allow skipping this check if needed
if [ "$SKIP_SRC_CHECK" = "1" ]; then
    exit 0
fi

set -e

# Colors for output
RED='\033[0;31m'
YELLOW='\033[1;33m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo "🔍 Checking for direct /src modifications..."

# Files that are auto-generated by scripts and may have legitimate uncommitted changes
# These are generated by various scripts and may change based on processing
SCRIPT_GENERATED_FILES=(
    "src/airtable-metadata.json"
    "src/relationships.json"
    "src/SUMMARY.md"  # Auto-generated by generate-summary-with-airtable.py
)

# Files that are auto-generated but should match their source-documents counterparts
# These should never have uncommitted changes unless source-documents changed
CONTENT_GENERATED_FILES=(
    "src/introduction.md"
)

# Directories where ALL files are auto-generated from source-documents/
GENERATED_DIRS=(
    "src/ordinances/"
    "src/resolutions/"
    "src/interpretations/"
    "src/other/"
    "src/agendas/"
    "src/minutes/"
    "src/transcripts/"
)

ISSUES_FOUND=false
WARNINGS_FOUND=false

# Check if running in git repository
if ! git rev-parse --git-dir > /dev/null 2>&1; then
    echo -e "${YELLOW}⚠️  Not in a git repository, skipping check${NC}"
    exit 0
fi

# Function to check if changes look auto-generated
is_likely_autogenerated() {
    local file=$1

    # For JSON files, check if the changes follow expected patterns
    if [[ "$file" == *.json ]]; then
        # Check if the file exists and has valid JSON structure
        if [ -f "$file" ] && python3 -m json.tool "$file" > /dev/null 2>&1; then
            return 0  # Likely auto-generated
        fi
    fi

    return 1  # Not clearly auto-generated
}

# Check script-generated files (these are allowed to have uncommitted changes)
echo "Checking script-generated metadata files..."
for file in "${SCRIPT_GENERATED_FILES[@]}"; do
    if [ -f "$file" ] && ! git diff --quiet HEAD -- "$file" 2>/dev/null; then
        if is_likely_autogenerated "$file"; then
            echo -e "${BLUE}ℹ️  Auto-generated changes detected: $file${NC}"
            echo "  These appear to be legitimate auto-generated updates."
            WARNINGS_FOUND=true
        else
            echo -e "${YELLOW}⚠️  Uncommitted changes in: $file${NC}"
            echo "  Please verify these are from running build scripts, not manual edits."
            WARNINGS_FOUND=true
        fi
    fi
done

# Check content-generated files (should match source-documents)
echo "Checking content-synced files..."
for file in "${CONTENT_GENERATED_FILES[@]}"; do
    if [ -f "$file" ] && ! git diff --quiet HEAD -- "$file" 2>/dev/null; then
        echo -e "${RED}✗ Direct modification detected: $file${NC}"
        echo "  This file is auto-generated. Edit the source files instead."
        ISSUES_FOUND=true
    fi
done

# Function to check if changes look like auto-formatting
is_likely_autoformatted() {
    local file=$1
    local diff_output=$(git diff HEAD -- "$file" 2>/dev/null)

    # Common auto-formatting patterns
    # - Signature formatting changes (comma removal, spacing)
    # - Table alignment changes
    # - Form field formatting
    # - Whitespace adjustments
    # - Number/list formatting (parentheses, indentation)
    # - Phone number formatting
    # - Footnote/div changes
    if echo "$diff_output" | grep -qE '(</span><br>,|</span><br> |form-field-empty|^\+\s*\|.*\||\-\s*\|.*\||STATE OF OREGON.*\)|County of.*\)|^\+\s*\([0-9]\)|^\-\s*[0-9]\.|503\.\s*639|<div class="footnotes">|^\+\s+\([0-9]+\)|^\-\s+[0-9]+\.)'; then
        return 0  # Likely auto-formatted
    fi

    # Check for markdown list formatting changes
    if echo "$diff_output" | grep -qE '(^\+\s+\([a-z]\)|^\-\s+[a-z]\.|^\+\s+[0-9]+\.|^\-\s+[0-9]+\.)'; then
        return 0  # List formatting change
    fi

    # Check if only whitespace or formatting changed
    if git diff -w --quiet HEAD -- "$file" 2>/dev/null; then
        return 0  # Only whitespace differences
    fi

    return 1  # Looks like manual edits
}

# Check for uncommitted changes in generated directories
for dir in "${GENERATED_DIRS[@]}"; do
    if [ -d "$dir" ]; then
        # Check if there are any modified files in this directory
        if ! git diff --quiet HEAD -- "$dir" 2>/dev/null; then
            modified_files=$(git diff --name-only HEAD -- "$dir" 2>/dev/null)
            if [ -n "$modified_files" ]; then
                # Check if corresponding source files were also modified
                has_manual_edits=false
                has_auto_changes=false
                for mod_file in $modified_files; do
                    # Convert src path to source-documents path
                    source_file=$(echo "$mod_file" | sed 's|^src/|source-documents/|')

                    # Check if changes look auto-generated
                    if is_likely_autoformatted "$mod_file"; then
                        has_auto_changes=true
                    # Also check if the file was recently synced (modified in last 5 minutes)
                    elif [ -f "$mod_file" ] && [ "$(find "$mod_file" -mmin -5 2>/dev/null)" ]; then
                        # Recently modified - likely by sync scripts
                        has_auto_changes=true
                    elif [ ! -f "$source_file" ] || git diff --quiet HEAD -- "$source_file" 2>/dev/null; then
                        # If source file doesn't exist or wasn't modified, and changes don't look auto-generated
                        has_manual_edits=true
                        break
                    fi
                done

                if [ "$has_manual_edits" = true ]; then
                    echo -e "${RED}✗ Direct modifications in $dir:${NC}"
                    echo "$modified_files" | sed 's/^/    /'
                    echo "  These files are auto-generated from source-documents/"
                    echo "  Edit the original files in source-documents/ instead."
                    ISSUES_FOUND=true
                elif [ "$has_auto_changes" = true ]; then
                    echo -e "${YELLOW}⚠️  Auto-generated changes detected in $dir${NC}"
                    echo "  These appear to be formatting changes from the build process."
                    WARNINGS_FOUND=true
                else
                    echo -e "${BLUE}ℹ️  Synced changes in $dir (from source-documents)${NC}"
                fi
            fi
        fi

        # Check for untracked files (new files added directly to /src)
        untracked=$(git ls-files --others --exclude-standard "$dir" 2>/dev/null)
        if [ -n "$untracked" ]; then
            echo -e "${YELLOW}⚠️  New untracked files in $dir:${NC}"
            echo "$untracked" | sed 's/^/    /'
            echo "  If these are meant to be permanent, add them to source-documents/ instead."
            ISSUES_FOUND=true
        fi
    fi
done

# Provide guidance based on findings
if [ "$ISSUES_FOUND" = true ]; then
    echo ""
    echo -e "${RED}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e "${RED}❌ Manual /src modifications detected!${NC}"
    echo ""
    echo "The /src directory contains auto-generated files that are"
    echo "created from source-documents/ by the build scripts."
    echo ""
    echo "To fix this:"
    echo "1. Copy your changes to the corresponding files in source-documents/"
    echo "2. Run: git checkout -- src/"
    echo "3. Run: ./build-all.sh"
    echo ""
    echo "This will regenerate /src from your source documents."
    echo -e "${RED}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    exit 1
elif [ "$WARNINGS_FOUND" = true ]; then
    echo ""
    echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e "${YELLOW}⚠️  Auto-generated changes detected${NC}"
    echo ""
    echo "Some auto-generated files have uncommitted changes."
    echo "This is normal after running build scripts."
    echo ""
    echo "If these changes are expected:"
    echo "• Review them with: git diff src/"
    echo "• Commit them if they're correct"
    echo ""
    echo "If these changes are unexpected:"
    echo "• Run: git checkout -- src/"
    echo "• Then run: ./build-all.sh"
    echo -e "${YELLOW}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    # Don't exit with error for warnings
    exit 0
else
    echo -e "${GREEN}✅ No manual /src modifications found${NC}"

    # Check if there are ANY uncommitted src changes (for informational purposes)
    if ! git diff --quiet HEAD -- "src/" 2>/dev/null; then
        echo -e "${BLUE}ℹ️  Note: There are uncommitted changes in src/ (appears to be auto-generated)${NC}"
    fi
fi