name: CSS Validation

on:
  push:
    branches: [ main ]
    paths:
      - 'custom.css'
      - 'theme/**'
      - 'scripts/**'
      - '.github/workflows/css-validation.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'custom.css'
      - 'theme/**'
      - 'scripts/**'

jobs:
  validate-css:
    name: Validate CSS Pipeline
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install mdBook
      run: |
        curl -sSL https://github.com/rust-lang/mdBook/releases/download/v0.4.35/mdbook-v0.4.35-x86_64-unknown-linux-gnu.tar.gz | tar -xz
        sudo mv mdbook /usr/local/bin/
    
    - name: Install Python dependencies
      run: |
        pip install beautifulsoup4
    
    - name: Verify custom.css is compiled
      run: |
        echo "Checking that custom.css is a compiled file..."
        if grep -q "^/\* COMPILED CSS - DO NOT EDIT DIRECTLY \*/" custom.css; then
          echo "✅ custom.css is properly compiled"
        else
          echo "❌ ERROR: custom.css doesn't appear to be compiled!"
          echo ""
          echo "custom.css should be generated by scripts/build/compile-css.py"
          echo "Run: python3 scripts/build/compile-css.py"
          exit 1
        fi
    
    - name: Verify theme structure
      run: |
        echo "Checking theme directory structure..."
        if [ ! -d "theme/css" ]; then
          echo "❌ ERROR: theme/css directory not found!"
          exit 1
        fi
        if [ ! -f "theme/css/main.css" ]; then
          echo "❌ ERROR: theme/css/main.css not found!"
          exit 1
        fi
        echo "✅ Theme structure is correct"
    
    - name: Run CSS pipeline tests
      run: |
        # Make scripts executable
        chmod +x scripts/validation/test-css-pipeline.sh
        chmod +x scripts/fix-styles.sh
        
        # Run the comprehensive test suite
        ./scripts/validation/test-css-pipeline.sh
    
    - name: Test mdBook build
      run: |
        echo "Testing mdBook build process..."
        mdbook build

        # Verify custom.css was copied correctly
        if [ ! -f "book/custom.css" ]; then
          echo "❌ ERROR: book/custom.css not created!"
          exit 1
        fi

        # Verify it's still the compiled version
        if ! grep -q "COMPILED CSS" book/custom.css; then
          echo "❌ ERROR: Compiled CSS not preserved during build!"
          exit 1
        fi

        echo "✅ mdBook build successful"
    
    - name: Verify CSS compilation
      run: |
        echo "Testing CSS compilation..."
        ./scripts/build/compile-css.py

        # Verify compilation worked
        if ! grep -q "COMPILED CSS" custom.css; then
          echo "❌ ERROR: CSS compilation failed!"
          exit 1
        fi

        echo "✅ CSS compilation works correctly"