name: Deploy mdBook to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v2
        with:
          mdbook-version: 'latest'
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install beautifulsoup4 python-dotenv requests pyairtable watchdog
          pip list | grep -E "beautifulsoup4|dotenv|requests|pyairtable|watchdog"
      
      - name: Build mdBook with processing
        env:
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
          AIRTABLE_BASE_ID: appnsWognX10X9TDL
        run: |
          chmod +x build-all.sh
          ./build-all.sh
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./book

      - name: Create issue on build failure
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            const title = '🚨 Deployment Build Failed';
            const body = `The deployment build failed for commit ${context.sha.substring(0, 7)}.

            **Workflow Run:** ${context.serverUrl}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}
            **Commit:** ${context.payload.head_commit.message}
            **Author:** @${context.payload.head_commit.author.username}

            Please check the workflow logs for details.`;

            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: title,
              body: body,
              labels: ['deployment', 'ci-failure']
            });

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4